"""MetaInfo 测试用运行时配置。"""

from functools import lru_cache

MEDIA_EXTS = [
    ".mp4",
    ".mkv",
    ".ts",
    ".iso",
    ".rmvb",
    ".avi",
    ".mov",
    ".mpeg",
    ".mpg",
    ".wmv",
    ".3gp",
    ".asf",
    ".m4v",
    ".flv",
    ".m2ts",
    ".strm",
    ".tp",
    ".f4v",
    ".srt",
    ".ass",
    ".ssa",
    ".sup",
    ".aac",
    ".ac3",
    ".amr",
    ".caf",
    ".cda",
    ".dsf",
    ".dff",
    ".kar",
    ".m4a",
    ".mp1",
    ".mp2",
    ".mp3",
    ".mid",
    ".mod",
    ".mka",
    ".mpc",
    ".nsf",
    ".ogg",
    ".pcm",
    ".rmi",
    ".s3m",
    ".snd",
    ".spx",
    ".tak",
    ".tta",
    ".vqf",
    ".wav",
    ".wma",
    ".aifc",
    ".aiff",
    ".alac",
    ".adif",
    ".adts",
    ".flac",
    ".midi",
    ".opus",
    ".sfalc",
]

RELEASE_GROUPS = {
    "0ff": ["FF(?:(?:A|WE)B|CD|E(?:DU|B)|TV)"],
    "1pt": [],
    "52pt": [],
    "audiences": ["Audies", "AD(?:Audio|E(?:book|)|Music|Web)"],
    "azusa": [],
    "beitai": ["BeiTai"],
    "btschool": ["Bts(?:CHOOL|HD|PAD|TV)", "Zone"],
    "carpt": ["CarPT"],
    "chdbits": ["CHD(?:Bits|PAD|(?:|HK)TV|WEB|)", "StBOX", "OneHD", "Lee", "xiaopie"],
    "discfan": [],
    "dragonhd": [],
    "eastgame": ["(?:(?:iNT|(?:HALFC|Mini(?:S|H|FH)D))-|)TLF"],
    "filelist": [],
    "gainbound": ["(?:DG|GBWE)B"],
    "hares": ["Hares(?:(?:M|T)V|Web|)"],
    "hd4fans": [],
    "hdarea": ["HDA(?:pad|rea|TV)", "EPiC"],
    "hdatmos": [],
    "hdbd": [],
    "hdchina": ["HDC(?:hina|TV|)", "k9611", "tudou", "iHD"],
    "hddolby": ["D(?:ream|BTV)", "(?:HD|QHstudI)o"],
    "hdfans": ["beAst(?:TV|)"],
    "hdhome": ["HDH(?:ome|Pad|TV|WEB|)"],
    "hdpt": ["HDPT(?:Web|)"],
    "hdsky": ["HDS(?:ky|TV|Pad|WEB|)", "AQLJ"],
    "hdtime": [],
    "HDU": [],
    "hdvideo": [],
    "hdzone": ["HDZ(?:one|)"],
    "hhanclub": ["HHWEB"],
    "hitpt": [],
    "htpt": ["HTPT"],
    "iptorrents": [],
    "joyhd": [],
    "keepfrds": ["FRDS", "Yumi", "cXcY"],
    "lemonhd": ["L(?:eague(?:(?:C|H)D|(?:M|T)V|NF|WEB)|HD)", "i18n", "CiNT"],
    "mteam": ["MTeam(?:TV|)", "MPAD", "MWeb"],
    "nanyangpt": [],
    "nicept": [],
    "oshen": [],
    "ourbits": ["Our(?:Bits|TV)", "FLTTH", "Ao", "PbK", "MGs", "iLove(?:HD|TV)"],
    "panda": ["Panda", "AilMWeb"],
    "piggo": ["PiGo(?:NF|(?:H|WE)B)"],
    "ptchina": [],
    "pterclub": ["PTer(?:DIY|Game|(?:M|T)V|WEB|)"],
    "pthome": ["PTH(?:Audio|eBook|music|ome|tv|WEB|)"],
    "ptmsg": [],
    "ptsbao": [
        "PTsbao",
        "OPS",
        "F(?:Fans(?:AIeNcE|BD|D(?:VD|IY)|TV|WEB)|HDMv)",
        "SGXT",
    ],
    "pttime": [],
    "putao": ["PuTao"],
    "soulvoice": [],
    "springsunday": ["CMCT(?:V|)"],
    "sharkpt": ["Shark(?:WEB|DIY|TV|MV|)"],
    "tccf": [],
    "tjupt": ["TJUPT"],
    "totheglory": ["TTG", "WiKi", "NGB", "DoA", "(?:ARi|ExRE)N"],
    "U2": [],
    "ultrahd": [],
    "others": [
        "B(?:MDru|eyondHD|TN)",
        "C(?:fandora|trlhd|MRG)",
        "DON",
        "EVO",
        "FLUX",
        "HONE(?:yG|)",
        "N(?:oGroup|T(?:b|G))",
        "PandaMoon",
        "SMURF",
        "T(?:EPES|aengoo|rollHD )",
    ],
    "anime": [
        "ANi",
        "HYSUB",
        "KTXP",
        "LoliHouse",
        "MCE",
        "Nekomoe kissaten",
        "SweetSub",
        "MingY",
        "(?:Lilith|NC)-Raws",
        "织梦字幕组",
        "枫叶字幕组",
        "猎户手抄部",
        "喵萌奶茶屋",
        "漫猫字幕社",
        "霜庭云花Sub",
        "北宇治字幕组",
        "氢气烤肉架",
        "云歌字幕组",
        "萌樱字幕组",
        "极影字幕社",
        "悠哈璃羽字幕社",
        "❀拨雪寻春❀",
        "沸羊羊(?:制作|字幕组)",
        "(?:桜|樱)都字幕组",
    ],
    "forge": ["FROG(?:E|Web|)"],
    "ubits": ["UB(?:its|WEB|TV)"],
}


def build_options(custom_words=None):
    """构造模拟 MoviePilot 调用方传入 Rust 扩展的解析配置。"""
    return _build_options_cached(tuple(custom_words or []))


@lru_cache(maxsize=64)
def _build_options_cached(custom_words):
    """复用 options 字典对象，匹配 MoviePilot 调用方的缓存行为。"""
    release_groups = []
    for site_groups in RELEASE_GROUPS.values():
        release_groups.extend(site_groups)
    return {
        "custom_words": list(custom_words),
        "media_exts": MEDIA_EXTS,
        "release_groups": "|".join(release_groups),
        "customization": [],
        "streaming_platforms": {},
    }
